config:
  cluster:
    enabled: true
    replicas: 2
  jetstream:
    enabled: true
    fileStore:
      pvc:
        enabled: true
        size: 2Gi
        storageClassName: standard
  merge:
    accounts:
      A:
        users:
        - {user: naresh, password: Admin123}
      B:
        users:
        - {user: anusha, password: Admin123}
